### ISSUE TITLE
Lesson Numbering

### ISSUE THREAD

**Issue by mjones01** [NEONInc/Deprecated-NEON-Template-Data-Skills#10]
(Probably belongs in Data Lessons but we can discuss here even if it applies elsewhere)

_As file names_:
@lwasser 14 De: The file names started with numbers because that is how Data Carpentry does it - IE there was a decision to name files that way that way so it is worth a conversation before changing the structure. Also we will need to consider how things will port over to NDS given some subtle structure differences.

@mjones 14 Dec: I'm just worried that when they go into the dataskills repo that all lesson 00s will be together instead of all Spatial Raster lessons grouped together. The Temporal Time Series lessons (TS00-name.) have been in this format since the Hack-a-thon.

_In Lesson Series Lists_:
@mjones 16 Dec: I can't decide if in the list they should be removed or not. I did in lesson 00 but then decided maybe it is nice... In the tabular time series, we now have the 07: Convert to Julian Day lesson. It is really an additional information lesson, not the 7th in a series. This is one of my issues with numbering. However, numbering does imply an order which most of the lesson series have.... I can't decide. All Spatial Rater have #s.

_In Lesson Text_:
@mjones 16 Dec: I removed #s from the lesson names when they are linked within the lesson. This is partially for stability over time in case lessons get re-numbered. Plus in the text the title is more important.

**Comment by lwasser** [comment]
@mjones01 i just left a comment about this in the time series repo. i think we should just number the lessons to be consistent. they live in directories with very clear naming so i think it should be ok for future. then all of the knit workflow is the same across repos.

**Comment by mjones01** [comment]
Agreed.  This Issue was started before we implemented the separate directories.  No need now.  Will address when I get to that PR. Closing.
