### ISSUE TITLE
new graphic for R package pages

### ISSUE THREAD

**Issue by lwasser** [NEONInc/Deprecated-NEON-Template-Data-Skills#15]
@coolinwilliams we will need a new set of images that are coding / informatics with "R" package on it. 

http://neoninc.github.io/NEONDS-Template-Repository/R-package/dplyr/

http://neoninc.github.io/NEONDS-Template-Repository/R-package/ggplot/
http://neoninc.github.io/NEONDS-Template-Repository/R-package/rgdal/

I think we can use the same banner for all pages. it just needs to have some sort of code theme, "R" and then packages.

Maybe it says Coding with R ?
@mjones01 any thoughts on what the graphics should look like?

**Comment by mjones01** [comment]
Didn't we get this? Close?

**Comment by lwasser** [comment]
we did! closing!
