### ISSUE TITLE
Jekyll 3.0 Migration

### ISSUE THREAD

**Issue by lwasser** [NEONInc/Deprecated-NEON-Template-Data-Skills#26]
@mjones01 Github is moving to a new upgraded version of Jekyll. They have more strict Markdown rules for instance.

    #hello  

Will not render as a header.

    # hello 

will.

we will likely need to update MANY lessons given this new, more strict convention. More to come as I figure out exactly how this will affect our sites. right now it's only affecting the lesson dev repo. i don't know why but have an email into git.

**Comment by mjones01** [comment]
Okay. I've been adding graphics to the Raster lessons. Should I be proactive and fix all the headers in the lessons now since I have most open?

**Comment by lwasser** [comment]
Yes please. Feel free to rebuild given it's just a header fix but please check each page after the build to make sure things still work:

  1.  Locally - it will hopefully look good
  2.  Online - this is where things are breaking given the 3.0 update.

NOTE: if code spacing begins to look funny, that is another Jekyll 3.0 adjustment that I'll need to make.
Thank you, Megan!

**Comment by mjones01** [comment]
I know you are working in Lesson Development repo but should I make the same changes to the Set Working Directory lesson since it has't yet been added to the repo (PR still pending)?  Just want to make sure I'm not interfering with your changes (it looks like there is at least 1 merge conflict now).

**Comment by lwasser** [comment]
I will fix the merge conflicts. When things broke yesterday I thought I had done something with a push. Turns out it was the jekyll update. Please go ahead and edit the lesson! I'll deal with the mess that is merge conflicts as I caused them. :)

**Comment by mjones01** [comment]
This is fixed in the example post: 74a4724

**Comment by lwasser** [comment]
ok - i think we have completed this - close? @mjones01

**Comment by mjones01** [comment]
Yep.
