### ISSUE TITLE
NDS Migration Issue - Rfigs image directory & code directory

### ISSUE THREAD

**Issue by lwasser** [NEONInc/Deprecated-NEON-Template-Data-Skills#27]
Currently, our `knitr` script dumps all images in an rfigs dir - path:

`images/rfigs`

This is fine for one set of lessons but when we are merging together 20+ lessons, many with the same starting 01, 02, etc it becomes confusing - especially knowing we will need to periodically clean this out upon rebuild. 

I propose that we add a subdir in rfigs called: **"dc-spatial-raster"** (the same dir name we use in `_posts/` to make it easier when we rebuild to clean out an set of old images. We can change each knitr file accordingly and update all 4 repos. I am happy to implement this if you are ok with it, @mjones01 

*NOTE: The same issue is going to pop up with the code dir - I will make a separate issue for that as it's more complicated to manage.

**Comment by mjones01** [comment]
Sounds good.  I also noticed that the Raster repo has the same naming system for non-r generated images (with change above: images/rfigs/dc-spatial-raster  and images/dc-spatial-raster).    However, the other two repos (vector & time series) have a different naming system.  I think at the same time we should change these names to match and keep a uniform system across all folders.  If you agree, I'll change the time series on this PR.

**Comment by lwasser** [comment]
DO you mean change
Images/tabTimeSeries<https://github.com/data-lessons/NEON-R-Tabular-Time-Series/tree/gh-pages/images/tabTimeSeries> -> dc-tabular-time-series
This would be a good change given that name is used in the posts dir. However you will have to update images throughout and rebuild. If you are going to rebuild, you should potentially rebuild using the new knitr code. Do you feel comfortable doing that?The knitr code needs a bit more tweaking. If you don't mind waiting, I will adjust so it's more programmatic and then send you a link as an issue in the time series repo.


Sounds good. I also noticed that the Raster repo has the same naming system for non-r generated images (with change above: images/rfigs/dc-spatial-raster and images/dc-spatial-raster). However, the other two repos (vector & time series) have a different naming system. I think at the same time we should change these names to match and keep a uniform system across all folders. If you agree, I'll change the time series on this PR.

-

**Comment by mjones01** [comment]
As this time series only has 1 image used at one location the manual change is easy (done yesterday as the figure code was not in our currently used format).  
I'm happy to use the new knitr code to rebuild especially since I'm having local build issues currently.  When do you think that knitr will be ready?

**Comment by lwasser** [comment]
Talk about timing I just finished it and pushed it up to the vector repo :)
NOTE: I'm just testing it in the spatial data intro repo now (where I'm currently working). So I may catch other bugs.
If you use it and find bugs, let me know!!  Thanks, Megan!

**Comment by lwasser** [comment]
closing this - as it was addressed.
