### ISSUE TITLE
Rendering Code in a Data Tip

### ISSUE THREAD

**Issue by mjones01** [NEONInc/Deprecated-NEON-Template-Data-Skills#32]
When the code is short, (below) works just find:

<i class="fa fa-star"></i> **Data Tip:** A custom function consists of a defined 
set of commands performed on a input object. Custom functions are particularly 
useful for tasks that need to be repeated over and over in the code. A simplified 
syntax for writing a custom function in R is:
	`functionName <- function(variable1, variable2){WhatYouWantDone, WhatToReturn}`
{: .notice }

However, when the code gets long it doesn't look as good: 

<i class="fa fa-star"></i> **Data Tip:** A custom function consists of a defined 
set of commands performed on a input object. Custom functions are particularly 
useful for tasks that need to be repeated over and over in the code. A simplified 
syntax for writing a custom function in R is:
`functionName <- function(variable1, variable2){ something_new <-do_something_to_variable1_and_variable2  return(something_new)}`
{: .notice }

Having a actual code chunk is one possibility but it necessitates two blue boxes which looks weird.  (.md code but the tabs disappeared): 

<i class="fa fa-star"></i> **Data Tip:** A custom function consists of a defined 
set of commands performed on a input object. Custom functions are particularly 
useful for tasks that need to be repeated over and over in the code. A simplified 
syntax for writing a custom function in R is:
{: .notice }
	 functionName <- function(
			variable1, variable2){
				something_new <- do_something_to_variable1_and_variable2
				return(something_new)
				}
{: .notice }

**Comment by lwasser** [comment]
move to dev? @mjones01

**Comment by mjones01** [comment]
moved: https://github.com/NEONInc/NEON-Data-Skills-Development/issues/26
