### ISSUE TITLE
moving issues

### ISSUE THREAD

**Issue by lwasser** [NEONInc/Deprecated-NEON-Template-Data-Skills#33]
Ok -- this repo had many issues associated with overall styling. We should consider which ones still are valid, which ones we can close. let's wait on moving them. I'm somewhat inclined to have template issues in the dev site as that is where we can test across all content types. Let's see what we can close in this template repo first!  @mjones01

**Comment by mjones01** [comment]
Nice job clearing out completed issue. Would you like to combine the two Challenge ones (mostly the shadow being cut off by figures) and move Challenge & Data Tip styling issue to Dev?  Then this repo is clear.

**Comment by lwasser** [comment]
sounds perfect! combine and move the challenge issue. we might want to move the other issue left in this repo to dev as well. 

phew - thanks! i'm very relieved to have one less repo to deal with. :)

**Comment by mjones01** [comment]
All addressed.  Delete repo?  (I don't have the capability to do this).

**Comment by lwasser** [comment]
For the time being let's just let it sit! We don't have to worry about it but we can leave it for now :) thank you!
