### ISSUE TITLE
Notice / Div Tags for breakout components

### ISSUE THREAD

**Issue by lwasser** [NEONInc/Deprecated-NEON-Template-Data-Skills#6]
We need styles for 

1. challenge code
2. breakout text
3. do we need a second level of breakout text styles??

**Comment by mjones01** [comment]
From PR #37
lwasser 15 Dec:
What is the difference between notice1 and 2?
i think this should be a discussion to make sure we need two formats.

mjones 16 Dec:
{: .notice1} is text with a non-shadowed, grey box. It is used in other NEON Data Skills lessons so I think it should be retained and is useful when something needs to stand out VERY separate from the lessons. However, as I read through lessons I find that this breaks the lesson up, setting the information apart from the lesson instead of as an integral part of the lesson, which it is.
          I'd started using the > at the start of the line as I found the formatting of a solid grey bar on both sides of the text a better way to highlight the Note but not separate it form the lesson. However, as you suggested, having > at the start of each line makes for messy code. You suggested a {: .notice2} could be created with that format to make for neater coding.

@mjones 16 Dec: Important considerations (and these may be wrong I don’t have 100% understanding of how they work):
- can’t be used on >1 paragraph.
- can’t be used with a code section in middle (based on error in SRL02).
- can’t be used with bullets

**Comment by mjones01** [comment]
Challenge Text: (From PR#37)
@lwasser, 15 Dec: I started using > to format challenges.
     We have a few options. We could also create a DIV tag that allows markdown. That could be the best option as it's fewer lines of code. We should start an issue on this in our style template. Or here and move it to the style template for final implementation.
     Essentially it seems you have some things you like and i have some i like and we will go back and forth on preferences unless we create an issue and define final style applications

@mjones, 16 Dec:  I’m inclined to shy away from > for the same (messy code) reasons as it wasn’t really liked for the notice.  While it works for shorter challenge sections some challenges are 10+ lines long.
     I’m more inclined to go with a DIV tag or simple use the *** to create a pale grey horizontal line before and after the challenge sections.
     When thinking about formatting I’d like to keep the challenged integrated with the lesson.  In a lot of modern text books they have bubbles, colored text blocks, etc to highlight different aspects.  When talking to students, and doing my own reading, I often hear that those sections are “extra” and can be skipped as they aren’t a core part.  I don’t want anyone to think that about the challenges.

@lwasser 15 Dec (but latter in PR after above response):  Ok Proposal. Let's create a new div style for challenges. Thikn about what it should look like. Then all challenges will be wrapped with:
</div>

**Comment by lwasser** [comment]
Let's also look at SWC's template. They have a nice set of styles for challenges, notes, breakouts, etc.
Then we can implement. So far i hear

1. We need a new div style for challenges.
2. we might revisit notice blocks, how they are used, what they look like and whether we need 1 or 2 styles to accomodate use cases. 

What are the notice block use cases? IE why might we need two styles or do we need two styles?

**Comment by lwasser** [comment]
Here is a SWC lesson

There have a few different types of breakouts

http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data.html

And a landing page for the entire "module"

**Comment by lwasser** [comment]
To help with this conversation, i have created a page with template items. we can use this to test all styles and document as well.

http://neoninc.github.io/NEONDS-Template-Repository//example-post/

Let's use the minimal mistakes documentation and our own documentation that we are creating to build out all options for buttons, headers, divs etc. We can then experiment with changes using this page while documenting all styles in one place!!

https://mmistakes.github.io/minimal-mistakes/

Note the data tip is the notice element. that was the original design from the theme i used to build the site. i really liked the simple little star. We could soften the colors to make it easier on the eyes and less abrupt.

**Comment by lwasser** [comment]
i am closing this as for now we have sorted this out. it may be revisited in the new design!
