### ISSUE TITLE
Grey Box Content Getting long

### ISSUE THREAD

**Issue by lwasser** [NEONInc/Deprecated-NEON-Template-Data-Skills#7]
What do we include in the box as text? What do we include as links to other pages with key background information.

**Comment by mjones01** [comment]
@lwasser suggestion for Challenge code: (from https://github.com/data-lessons/NEON-R-Spatial-Raster/pull/37) NEON Data lessons include challenges that reinforce learned skills. Solutions for each challenge, can be found in the R code, available for download on the bottom of each lesson page.

**Comment by mjones01** [comment]
Find/Replace: 
Images should be credited to NEON rather than NEON, Inc   (https://github.com/data-lessons/NEON-R-Spatial-Vector/issues/56)

**Comment by mjones01** [comment]
This mostly seems to be addressed.  We might change some of the grey box with the move to a new website layout anyway.  Close?

**Comment by lwasser** [comment]
yes - let's close :)
