### ISSUE TITLE
Code denotation `word`

### ISSUE THREAD

**Issue by mjones01** [NEONInc/Deprecated-NEON-Template-Data-Skills#9]
@mjones 16 Dec: I used the code format when it was applying to the R entity but not if it was a concept in general. A bit confusing when the terms are the same, but it applies easily when the code term is different or only a small part of the full term. Here we are thinking about CRSs in general not the CRS in a particular R object. Is that too confusing?

**Comment by lwasser** [comment]
we just talked about this yesterday. i'm ok with using CRS in a **bold** font and then `crs()` when referring to the function

**Comment by mjones01** [comment]
Perfect.  Added text to this effect in Example Post (now in Lesson Building repo).  Closing.
